- name: integrate argoCD
  import_tasks: argo.yaml

- name: integrate kafka
  import_tasks: kafka.yaml
  
- name: Copy kafka-automation.yaml.j2 to remote host
  ansible.builtin.template:
    src: kafka-automation.yaml.j2
    dest: /tmp/kafka-automation.yaml
    
- name: Copy kafka-automation.yaml.j2 to remote host
  ansible.builtin.template:
    src: kafka-automation.yaml.j2
    dest: /tmp/kafka-automation.yaml

