- name: integrate argoCD
  import_tasks: argo.yaml

- name: integrate kafka
  import_tasks: kafka.yaml
  
- name: Render kafka-automation.yaml locally
  ansible.builtin.template:
    src: kafka-automation.yaml.j2
    dest: /tmp/kafka-automation.yaml
  delegate_to: localhost
  run_once: true

- name: Log first 20 lines of the rendered YAML
  ansible.builtin.shell: "head -n 20 /tmp/kafka-automation.yaml"
  delegate_to: localhost
  run_once: true
  register: rendered_yaml_head

- name: Display rendered YAML head
  ansible.builtin.debug:
    msg: "{{ rendered_yaml_head.stdout }}"
  delegate_to: localhost
  run_once: true
