- name: integrate argoCD
  import_tasks: argo.yaml

- name: integrate kafka
  import_tasks: kafka.yaml

- name: integrate prometheus
  import_tasks: prometheus.yaml

- name: integrate alertmanager
  import_tasks: alertmanager.yaml

- name: integrate grafana
  import_tasks: grafana.yaml
