- name: Install Helm
  ansible.builtin.command: sudo snap install helm --classic
  when: inventory_hostname in groups['control-plane']

- name: Add Prometheus community repo
  ansible.builtin.command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
  when: inventory_hostname in groups['control-plane']

- name: Add stable Helm repo
  ansible.builtin.command: helm repo add stable https://charts.helm.sh/stable
  when: inventory_hostname in groups['control-plane']

- name: Update Helm repositories
  ansible.builtin.command: helm repo update
  when: inventory_hostname in groups['control-plane']

- name: Create monitoring namespace
  command: kubectl --kubeconfig=/home/asmae/.kube/config create namespace monitoring
  when: inventory_hostname in groups['control-plane']

- name: Install kube-prometheus-stack
  ansible.builtin.command: >
    helm install prometheus prometheus-community/kube-prometheus-stack
    --namespace monitoring
    --kubeconfig=/home/asmae/.kube/config 
  when: inventory_hostname in groups['control-plane']

- name: Patch prometheus-grafana service to NodePort
  ansible.builtin.command: >
    kubectl patch svc prometheus-grafana 
    -n monitoring 
    -p '{"spec": {"type": "NodePort"}}'
    --kubeconfig=/home/asmae/.kube/config 
  when: inventory_hostname in groups['control-plane']
