apiVersion: v1
kind: Service
metadata:
  name: express-backend
  namespace: default
spec:
  selector:
    app: express-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP