apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-backend
  template:
    metadata:
      labels:
        app: express-backend
    spec:
      containers:
      - name: express-backend
        image: soulayman379/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          volumeMounts:
            - name: key-file-volume
              mountPath: /secrets
              readOnly: true
      volumes:
        - name: key-file-volume
          hostPath:
            path: /tmp/key-file.json
            type: File