apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-backend
  template:
    metadata:
      labels:
        app: express-backend
    spec:
      containers:
      - name: express-backend
        image: soulayman379/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: env-file-volume
          mountPath: /app/env.conf
          subPath: env.conf
        - name: key-file-volume
          mountPath: /tmp
          readOnly: true
      volumes:
      - name: env-file-volume
        hostPath:
          path: /etc/kubernetes/env.conf
          type: File
      - name: key-file-volume
        hostPath:
          path: /tmp/key-file.json
          type: File