apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-backend
  template:
    metadata:
      labels:
        app: express-backend
    spec:
      containers:
      - name: express-backend
        image: soulayman379/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: backend-env
              key: SERVER_ADDRESS
        volumeMounts:
        - name: key-file-volume
          mountPath: /tmp
          readOnly: true
      volumes:
      - name: key-file-volume
        secret:
          secretName: gcp-key-file
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-env
data:
  SERVER_ADDRESS: "${SERVER_ADDRESS}"