apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-backend
  template:
    metadata:
      labels:
        app: express-backend
    spec:
      containers:
      - name: express-backend
        image: express-backend
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: gcp-key-volume
          mountPath: /tmp
          readOnly: true
      volumes:
      - name: gcp-key-volume
        secret:
          secretName: gcp-key-secret