apiVersion: v1
kind: Service
metadata:
  name: react-frontend
spec:
  type: NodePort  # Change from LoadBalancer to NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: react-frontend