- name: Update and upgrade apt packages
  apt:
    update_cache: yes
    upgrade: dist

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Prepare apt keyring directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: 0755
  
- name: Add Kubernetes apt key
  ansible.builtin.get_url:
    url: "https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key"
    dest: /etc/apt/keyrings/kubernetes-apt-keyring.asc
    mode: '0644'
    force: true
  
- name: Add Kubernetes apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.asc] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /"
    state: present
    filename: kubernetes
    update_cache: yes

- name: Ensure swap is disabled
  shell: |
    swapoff -a
    sed -i '/ swap / s/^/#/' /etc/fstab
  args:
    executable: /bin/bash

- name: Load kernel modules
  copy:
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
    dest: /etc/sysctl.d/k8s.conf
  notify: Apply sysctl changes

- name: Ensure br_netfilter kernel module is loaded
  ansible.builtin.shell: |
    modprobe br_netfilter
    echo 'br_netfilter' > /etc/modules-load.d/br_netfilter.conf
  args:
    executable: /bin/bash

- name: Apply sysctl changes for Kubernetes
  ansible.builtin.shell: sysctl --system
  args:
    executable: /bin/bash
