name: CI/CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/mock-app:${{ github.run_number }} .

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.18.3
      
      - name: Scan Docker Image with Trivy
        run: |
           trivy image --severity HIGH,CRITICAL  ${{ secrets.DOCKER_USERNAME }}/mock-app:${{ github.run_number }}

      - name: Push Docker Image to DockerHub
        # if: success() 
        run: docker push ${{ secrets.DOCKER_USERNAME }}/mock-app:${{ github.run_number }}

      - name: Update Image Version in Kubernetes Manifests
        # if: success() 
        run: |
          find manifests/ -type f -name "*.yaml" -exec sed -i 's|image: ${{ secrets.DOCKER_USERNAME }}/mock-app:.*|image: ${{ secrets.DOCKER_USERNAME }}/mock-app:${{ github.run_number }}|g' {} \;

      - name: Commit and push if there are changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add manifests/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update image version to ${{ github.run_number }}" && git push)